name: SizeV1
version: 1.0.0-BETA
main: ySimmer\Size\Main
api: 5.0.0
author: ySimmer/yRobx
description: Primera version de size

commands:
  size:
    description: Size command
    usage: "/size <set|reset|credits|help> [valor] [jugador]"
    permission: size.use

permissions:
  size.use:
    description: Permite usar comandos básicos do size
    default: op
  size.others:
    description: Permite alterar tamanho de outros jogadores
    default: op
  size.admin:
    description: Acesso completo aos comandos
    default: op
